server:
  port: 6600
spring:
  application:
    name: nacos-provider-movie6600
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos\u670D\u52A1\u7AEF\u5730\u5740
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
feign:
  sentinel:
    enabled: true